[features]
seeds = false
skip-lint = false

[programs.devnet]
triad = "Fire3T9ABT33UYoVJZwWUnbPR3rgoVw98y82UgHZ8Bm"

[registry]
url = "https://devnet.helius-rpc.com/?api-key=99a121c0-a036-4c3d-a853-03623d1d2390"

[provider]
cluster = "Devnet"
wallet = "/Users/dannpl/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
